"""Initial NCMS schema

Revision ID: 23d7b3f0cdd3
Revises: 
Create Date: 2026-07-28 22:27:41.777035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d7b3f0cdd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_history_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('panchayaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'name', name='uq_campaign_panchayath')
    )
    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panchayaths_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panchayaths_name'), ['name'], unique=False)

    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('panchayath_id', sa.Integer(), nullable=False),
    sa.Column('squad_no', sa.Integer(), nullable=False),
    sa.Column('squad_days', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('submission_token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['panchayath_id'], ['panchayaths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'squad_no', name='uq_campaign_squad')
    )
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_panchayath_id'), ['panchayath_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_squad_no'), ['squad_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_submission_token'), ['submission_token'], unique=True)

    op.create_table('squad_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=100), nullable=True),
    sa.Column('pashudhan_id', sa.String(length=50), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_members_squad_id'), ['squad_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=True),
    sa.Column('vaccinations_done', sa.Integer(), nullable=True),
    sa.Column('pashudhan_entries', sa.Integer(), nullable=True),
    sa.Column('diseased', sa.Integer(), nullable=True),
    sa.Column('below_4_months', sa.Integer(), nullable=True),
    sa.Column('pregnant', sa.Integer(), nullable=True),
    sa.Column('unwilling', sa.Integer(), nullable=True),
    sa.Column('other_reason', sa.String(length=250), nullable=True),
    sa.Column('other_count', sa.Integer(), nullable=True),
    sa.Column('vaccination_percentage', sa.Float(), nullable=True),
    sa.Column('pashudhan_percentage', sa.Float(), nullable=True),
    sa.Column('vaccination_reason', sa.Text(), nullable=True),
    sa.Column('pashudhan_reason', sa.Text(), nullable=True),
    sa.Column('submitted_from', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_status'))

    op.drop_table('submissions')
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_members_squad_id'))

    op.drop_table('squad_members')
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squads_submission_token'))
        batch_op.drop_index(batch_op.f('ix_squads_status'))
        batch_op.drop_index(batch_op.f('ix_squads_squad_no'))
        batch_op.drop_index(batch_op.f('ix_squads_panchayath_id'))
        batch_op.drop_index(batch_op.f('ix_squads_campaign_id'))

    op.drop_table('squads')
    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panchayaths_name'))
        batch_op.drop_index(batch_op.f('ix_panchayaths_campaign_id'))

    op.drop_table('panchayaths')
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_history_campaign_id'))

    op.drop_table('import_history')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_code'))

    op.drop_table('campaigns')
    # ### end Alembic commands ###
