"""Add remarks field to submission

Revision ID: 47e15183de88
Revises: 23d7b3f0cdd3
Create Date: 2026-07-29 07:41:43.829928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e15183de88'
down_revision = '23d7b3f0cdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.alter_column('office',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('pashudhan_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_squad_members_pashudhan_id'), ['pashudhan_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_members_pashudhan_id'))
        batch_op.alter_column('pashudhan_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('office',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
