"""Add submission history for resubmissions

Revision ID: 493bc878b2a4
Revises: b8f65ced1aa9
Create Date: 2026-08-09 06:16:19.299695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493bc878b2a4'
down_revision = 'b8f65ced1aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('submission_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_submission_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=True),
    sa.Column('vaccinations_done', sa.Integer(), nullable=True),
    sa.Column('pashudhan_entries', sa.Integer(), nullable=True),
    sa.Column('diseased', sa.Integer(), nullable=True),
    sa.Column('below_4_months', sa.Integer(), nullable=True),
    sa.Column('pregnant', sa.Integer(), nullable=True),
    sa.Column('unwilling', sa.Integer(), nullable=True),
    sa.Column('other_reason', sa.String(length=250), nullable=True),
    sa.Column('other_count', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('vaccination_percentage', sa.Float(), nullable=True),
    sa.Column('pashudhan_percentage', sa.Float(), nullable=True),
    sa.Column('vaccination_reason', sa.Text(), nullable=True),
    sa.Column('pashudhan_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submission_token', sa.String(length=30), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('archived_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_history_original_submission_id'), ['original_submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_history_squad_id'), ['squad_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_history_squad_id'))
        batch_op.drop_index(batch_op.f('ix_submission_history_original_submission_id'))

      # ### end Alembic commands ###