"""Update Squad model

Revision ID: 4f2dd38c28fe
Revises: 1fdfbff7cea7
Create Date: 2026-07-26 09:18:32.172289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2dd38c28fe'
down_revision = '1fdfbff7cea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_campaigns_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_campaigns_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panchayaths_name'), ['name'], unique=True)

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Integer(), nullable=True))
        batch_op.alter_column('submission_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_squads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_panchayath_id'), ['panchayath_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_squad_no'), ['squad_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('uq_campaign_squad', ['campaign_id', 'squad_no'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_status'))

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_campaign_squad', type_='unique')
        batch_op.drop_index(batch_op.f('ix_squads_status'))
        batch_op.drop_index(batch_op.f('ix_squads_squad_no'))
        batch_op.drop_index(batch_op.f('ix_squads_panchayath_id'))
        batch_op.drop_index(batch_op.f('ix_squads_campaign_id'))
        batch_op.alter_column('submission_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('target')

    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panchayaths_name'))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_campaigns_code'), ['code'])

    # ### end Alembic commands ###
