"""Add campaign submission control

Revision ID: 69be8b1e90e0
Revises: 5a505053058c
Create Date: 2026-08-03 16:35:37.190391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69be8b1e90e0'
down_revision = '5a505053058c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submissions_open', sa.Boolean(), server_default='1', nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('submissions_open')

    # ### end Alembic commands ###
