"""Add designation to squad members

Revision ID: f10970896fe9
Revises: 69be8b1e90e0
Create Date: 2026-08-03 22:08:10.940064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10970896fe9'
down_revision = '69be8b1e90e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
