"""Initial NCMS database

Revision ID: f5d5035acd77
Revises: 352554277cf0
Create Date: 2026-07-22 11:41:17.482831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d5035acd77'
down_revision = '352554277cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('panchayath_id', sa.Integer(), nullable=False),
    sa.Column('squad_no', sa.Integer(), nullable=False),
    sa.Column('squad_days', sa.Integer(), nullable=True),
    sa.Column('squad_member', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=200), nullable=True),
    sa.Column('pashudhan_id', sa.String(length=100), nullable=False),
    sa.Column('submission_token', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['panchayath_id'], ['panchayaths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_token')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=True),
    sa.Column('vaccinations_done', sa.Integer(), nullable=True),
    sa.Column('pashudhan_entries', sa.Integer(), nullable=True),
    sa.Column('diseased', sa.Integer(), nullable=True),
    sa.Column('below_4_months', sa.Integer(), nullable=True),
    sa.Column('pregnant', sa.Integer(), nullable=True),
    sa.Column('unwilling', sa.Integer(), nullable=True),
    sa.Column('other_reason', sa.String(length=250), nullable=True),
    sa.Column('other_count', sa.Integer(), nullable=True),
    sa.Column('vaccination_percentage', sa.Float(), nullable=True),
    sa.Column('pashudhan_percentage', sa.Float(), nullable=True),
    sa.Column('vaccination_reason', sa.Text(), nullable=True),
    sa.Column('pashudhan_reason', sa.Text(), nullable=True),
    sa.Column('submitted_from', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panchayaths', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')

    op.drop_table('submissions')
    op.drop_table('squads')
    # ### end Alembic commands ###
